name:                haskell-operden
version:             0.1.0.0
github:              "githubuser/haskell-operden"
license:             MIT
author:              "Pzixel"
maintainer:          "pzixel@gmail.com"
copyright:           "2020 Pzixel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Operden written in Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Pzixel/haskell-operden>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- base-compat
- blaze-html
- blaze-markup
- bytestring
- conduit
- directory
- esqueleto
- http-media
- lens
- lucid
- monad-logger
- mtl
- persistent
- persistent-postgresql
- persistent-template
- servant
- servant-server
- servant-swagger
- servant-swagger-ui
- string-conversions
- swagger2
- text
- time
- wai
- warp

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  haskell-operden-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-operden

tests:
  haskell-operden-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-operden

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeOperators
